clevercanary/data-explorer

packages/data-explorer-ui/README.md, packages/data-explorer-ui/package-lock.json, packages/data-explorer-ui/package.json
=> feat: test and update instructions about running along side data-browser locally (#52)

packages/data-explorer-ui/README.md
=> feat: test data-explorer-ui and running along side data-browser instructions (#54)

packages/data-explorer-ui/package-lock.json, packages/data-explorer-ui/package.json, packages/data-explorer-ui/src/components/common/KeyValuePairs/components/KeyValueElType/keyValueElType.styles.ts, packages/data-explorer-ui/src/components/common/KeyValuePairs/components/KeyValueElType/keyValueElType.tsx, packages/data-explorer-ui/src/components/common/KeyValuePairs/keyValuePairs.tsx
=> feat: update keyvaluepairs component to take a function on the keyvalue element (#60)

packages/data-explorer-ui/package.json, packages/data-explorer-ui/src/config/entities.ts
Closes clevercanary/data-browser#830.
=> feat: added GTM auth to enable environments #830

packages/data-explorer-ui/src/components/common/Breadcrumbs/breadcrumbs.stories.tsx
Closes #88 
Adds Breadcrumb stories to the Storybook
=> feat: add breadcrumb stories on storybook (#88)

packages/data-explorer-ui/src/components/common/Button/components/CallToActionButton/calltoActionButton.stories.tsx
Closes #90 
Adds CallToActionButton stories on storybook.
=> feat: add callToActionButton stories on storybook (#90)

packages/data-explorer-ui/src/components/common/CopyToClipboard/copyToClipboard.stories.tsx
=> feat: add story to copyToClipboard component (#99)

packages/data-explorer-ui/src/components/common/Tabs/tabs.tsx
=> feat: allow tabs to have counters (#108)

packages/data-explorer-ui/package-lock.json, packages/data-explorer-ui/package.json, packages/data-explorer-ui/src/components/Table/common/utils.ts, packages/data-explorer-ui/src/components/Table/components/DownloadEntityResults/downloadEntityResults.tsx, packages/data-explorer-ui/src/components/Table/table.styles.ts, packages/data-explorer-ui/src/components/Table/table.tsx, packages/data-explorer-ui/src/components/TableCreator/tableCreator.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/views/ExploreView/exploreView.tsx, packages/data-explorer-ui/tsconfig.json
=> feat: add download button to table (#142)

packages/data-explorer-ui/src/components/Project/common/entities.ts, packages/data-explorer-ui/src/components/Project/components/Citation/citation.stories.tsx, packages/data-explorer-ui/src/components/Project/components/Citation/citation.tsx
=> feat: update citation component prop projectpath to projecturl (#141)

packages/data-explorer-ui/src/components/common/CustomIcon/customIcon.stories.tsx, packages/data-explorer-ui/src/components/common/CustomIcon/customIcon.tsx
=> feat: add story to customIcon (#101)

packages/data-explorer-ui/.storybook/preview-head.html, packages/data-explorer-ui/src/components/Error/error.stories.tsx, packages/data-explorer-ui/src/components/Error/error.styles.ts, packages/data-explorer-ui/src/components/Error/error.tsx, packages/data-explorer-ui/src/components/common/Section/section.styles.ts
Closes #117 
Updates Error component to show Request URL and Error Message if provided.
=> feat: update Error component (#117) 

packages/data-explorer-ui/src/components/Links/links.tsx
=> fix: update links component key with an iterator (#164)

packages/data-explorer-ui/src/common/utils.ts, packages/data-explorer-ui/src/components/Links/components/Link/link.tsx, packages/data-explorer-ui/src/components/common/Card/card.stories.tsx, packages/data-explorer-ui/src/components/common/Card/card.styles.ts, packages/data-explorer-ui/src/components/common/Card/card.tsx, packages/data-explorer-ui/src/components/common/Card/components/CardAction/cardAction.tsx, packages/data-explorer-ui/src/components/common/Card/components/CardActionArea/cardActionArea.tsx, packages/data-explorer-ui/src/components/common/Card/components/CardActions/cardActions.styles.ts, packages/data-explorer-ui/src/components/common/Card/components/CardActions/cardActions.tsx, packages/data-explorer-ui/src/components/common/Card/components/CardMedia/cardMedia.styles.ts, packages/data-explorer-ui/src/components/common/Card/components/CardMedia/cardMedia.tsx, packages/data-explorer-ui/src/components/common/Card/components/CardSecondaryText/cardSecondaryText.tsx, packages/data-explorer-ui/src/components/common/Card/components/CardSecondaryTitle/cardSecondaryTitle.styles.ts, packages/data-explorer-ui/src/components/common/Card/components/CardSecondaryTitle/cardSecondaryTitle.tsx, packages/data-explorer-ui/src/components/common/Card/components/CardText/cardText.tsx, packages/data-explorer-ui/src/components/common/Card/components/CardTitle/cardTitle.tsx, packages/data-explorer-ui/src/components/common/Card/components/RoundedCard/roundedCard.tsx, packages/data-explorer-ui/src/theme/common/components.ts, packages/data-explorer-ui/src/theme/theme.ts
Closes #214
Closes https://github.com/DataBiosphere/findable-ui/issues/6
=> feat: create card component (#214)

packages/data-explorer-ui/src/components/TempError/components/errorBox.tsx, packages/data-explorer-ui/src/components/TempError/index.ts, packages/data-explorer-ui/src/components/TempError/tempError.tsx
=> feat: adding temp eror component #68

packages/data-explorer-ui/src/apis/azul/common/filterTransformer.ts, packages/data-explorer-ui/src/apis/azul/common/utils.ts, packages/data-explorer-ui/src/components/Export/common/utils.ts, packages/data-explorer-ui/src/components/Export/components/ExportEntityToTerra/exportEntityToTerra.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/ExportToTerraNotStarted/exportToTerraNotStarted.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/ExportToTerraReady/exportToTerraReady.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/exportToTerra.styles.ts, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/exportToTerra.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerraNotStarted/exportToTerraNotStarted.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerraReady/exportToTerraReady.stories.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerraReady/exportToTerraReady.tsx, packages/data-explorer-ui/src/components/common/Code/code.stories.tsx, packages/data-explorer-ui/src/components/common/Code/code.styles.ts, packages/data-explorer-ui/src/components/common/Code/code.tsx, packages/data-explorer-ui/src/components/common/MDXMarkdown/components/Section/mdxSection.styles.ts, packages/data-explorer-ui/src/hooks/useDetailState.tsx, packages/data-explorer-ui/src/providers/detailState.tsx, packages/data-explorer-ui/src/theme/common/components.ts, packages/data-explorer-ui/src/views/EntityDetailView/entityDetailView.tsx
Closes #221.
Closes https://github.com/DataBiosphere/findable-ui/issues/27.
=> feat: implement export entity to Terra (#221)

packages/data-explorer-ui/src/components/Layout/components/ContentLayout/contentLayout.styles.ts, packages/data-explorer-ui/src/components/Layout/components/ContentLayout/contentLayout.tsx, packages/data-explorer-ui/src/components/Layout/components/Nav/components/NavBarHero/navBarHero.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Nav/components/NavBarHero/navBarHero.tsx, packages/data-explorer-ui/src/components/Layout/components/Nav/nav.stories.tsx, packages/data-explorer-ui/src/components/Layout/components/Nav/nav.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Nav/nav.tsx, packages/data-explorer-ui/src/theme/common/components.ts, packages/data-explorer-ui/src/views/ContentView/contentView.stories.tsx, packages/data-explorer-ui/src/views/ContentView/contentView.tsx
Closes #226.
Closes https://github.com/DataBiosphere/findable-ui/issues/8
=> feat: create nav component (#226)

packages/data-explorer-ui/src/components/common/Accordion/accordion.stories.tsx, packages/data-explorer-ui/src/components/common/Accordion/accordion.tsx, packages/data-explorer-ui/src/components/common/CustomIcon/components/AddIcon/addIcon.tsx, packages/data-explorer-ui/src/components/common/CustomIcon/components/RemoveIcon/removeIcon.tsx, packages/data-explorer-ui/src/theme/common/components.ts, packages/data-explorer-ui/src/theme/theme.ts
Closes #231.
Closes https://github.com/DataBiosphere/findable-ui/issues/9.
=> feat: create accordion component (#231)

packages/data-explorer-ui/src/components/common/Button/components/ButtonSecondary/buttonSecondary.tsx, packages/data-explorer-ui/src/components/common/Button/components/ButtonSecondaryOutline/buttonSecondaryOutline.tsx, packages/data-explorer-ui/src/theme/common/components.ts, packages/data-explorer-ui/src/theme/common/palette.ts, packages/data-explorer-ui/src/theme/theme.ts
=> feat: create secondary outline button (#246)

packages/data-explorer-ui/src/components/Detail/components/Table/table.tsx, packages/data-explorer-ui/src/components/common/Banner/banner.tsx, packages/data-explorer-ui/src/components/common/Breadcrumbs/breadcrumbs.tsx, packages/data-explorer-ui/src/components/common/ButtonGroup/buttonGroup.tsx, packages/data-explorer-ui/src/components/common/ButtonGroup/components/ButtonGroupButton/buttonGroupButton.tsx, packages/data-explorer-ui/src/components/common/RadioGroup/radioGroup.tsx, packages/data-explorer-ui/src/components/common/Tabs/tabs.tsx
=> feat: add classname prop to components (#250)

packages/data-explorer-ui/src/components/Detail/components/DetailViewTable/detailViewTable.tsx, packages/data-explorer-ui/src/components/NoResults/noResults.tsx
=> feat: update detailviewtable and noresults with paper prop (#252)

packages/data-explorer-ui/src/components/Layout/components/ContentLayout/contentLayout.styles.ts
=> feat: remove paragraph font from contentlayout component (#260)

packages/data-explorer-ui/src/hooks/useURLFilterParams.ts
=> fix: imports in useurlfilterparams hook (#223)

packages/data-explorer-ui/src/entity/api/client.ts
Closes https://github.com/clevercanary/data-explorer/issues/273
=> feat: extending timeout to 20 sec #273

packages/data-explorer-ui/src/components/Table/common/utils.ts, packages/data-explorer-ui/src/components/Table/table.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/hooks/useEntityList.ts, packages/data-explorer-ui/src/providers/exploreState.tsx
Closes https://github.com/clevercanary/data-explorer/issues/272
=> feat: creating a state to keep index config data for each entity #272

packages/data-explorer-ui/package-lock.json, packages/data-explorer-ui/package.json, packages/data-explorer-ui/src/components/Filter/common/constants.ts, packages/data-explorer-ui/src/components/Filter/components/FilterMenu/filterMenu.styles.ts, packages/data-explorer-ui/src/components/Filter/components/FilterMenu/filterMenu.tsx, packages/data-explorer-ui/src/components/Filter/components/VariableSizeList/VariableSizeList.tsx, packages/data-explorer-ui/src/components/Filter/components/VariableSizeListItem/variableSizeListItem.tsx
=> feat: use virtualized list for filter dropdowns (#248)

packages/data-explorer-ui/src/components/Filter/components/VariableSizeList/VariableSizeList.tsx
=> fix: fix virtualised list height (#282)

packages/data-explorer-ui/package-lock.json, packages/data-explorer-ui/package.json, packages/data-explorer-ui/src/components/Filter/components/Filter/filter.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/NavLinkMenu/navLinkMenu.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/ProfileComponent/components/AuthenticationMenu/authenticationMenu.tsx, packages/data-explorer-ui/src/components/Table/components/CheckboxMenu/checkboxMenu.tsx
=> chore: update mui package to latest (#284)

packages/data-explorer-ui/src/components/Filter/components/Filters/filters.stories.tsx, packages/data-explorer-ui/src/components/Filter/components/Filters/filters.styles.ts, packages/data-explorer-ui/src/components/Filter/components/Filters/filters.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/hooks/useCategoryConfigs.ts, packages/data-explorer-ui/src/hooks/useCategoryFilter.ts, packages/data-explorer-ui/src/providers/exploreState.tsx, packages/data-explorer-ui/src/views/ExploreView/exploreView.tsx
=> feat: refactor filter categories to support filter groups (#300)

packages/data-explorer-ui/src/components/Index/components/TitleCell/titleCell.styles.ts, packages/data-explorer-ui/src/components/Index/components/TitleCell/titleCell.tsx
=> feat: double decker table column component (#295)

packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/ExportToTerraReady/exportToTerraReady.tsx, packages/data-explorer-ui/src/components/common/Alert/alert.stories.tsx
=> feat: do not open terra links automatically in "export to terra" flow (#317)

packages/data-explorer-ui/src/hooks/useFileManifest/common/utils.ts
=> fix: fix binding of term facets for selected null values (#322)

packages/data-explorer-ui/src/components/Detail/detail.stories.tsx, packages/data-explorer-ui/src/components/Layout/components/BackPage/backPageView.stories.tsx, packages/data-explorer-ui/src/components/Layout/components/BackPage/components/BackPageHero/backPageHero.stories.tsx, packages/data-explorer-ui/src/components/Layout/components/BackPage/components/BackPageHero/backPageHero.styles.ts, packages/data-explorer-ui/src/components/Layout/components/BackPage/components/BackPageHero/backPageHero.tsx, packages/data-explorer-ui/src/components/common/Button/components/ButtonText/buttonText.styles.ts, packages/data-explorer-ui/src/components/common/Button/components/ButtonTextPrimary/buttonTextPrimary.styles.ts, packages/data-explorer-ui/src/components/common/Button/components/ButtonTextPrimary/buttonTextPrimary.tsx, packages/data-explorer-ui/src/components/common/StatusBadge/statusBadge.stories.tsx, packages/data-explorer-ui/src/components/common/StatusBadge/statusBadge.tsx, packages/data-explorer-ui/src/theme/common/components.ts
=> feat: refactor status badge to be more flexible (#324)

packages/data-explorer-ui/src/components/Index/index.stories.tsx, packages/data-explorer-ui/src/components/Index/index.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/views/ExploreView/exploreView.tsx
=> feat: refactor explore and index view components to be more flexible (#325)

packages/data-explorer-ui/src/components/ComponentCreator/ComponentCreator.tsx, packages/data-explorer-ui/src/components/ComponentCreator/components/ConditionalComponent/conditionalComponent.tsx, packages/data-explorer-ui/src/components/Layout/components/BackPage/backPageView.tsx, packages/data-explorer-ui/src/config/entities.ts
=> feat: create detailed page flexibility including support for conditional component rendering (#329)

packages/data-explorer-ui/src/hooks/useFileManifest/useFetchFilesFacets.ts, packages/data-explorer-ui/src/hooks/useFileManifest/useFetchSummary.ts
=> feat: send auth token when requesting summary and files for export pages (#333)

packages/data-explorer-ui/src/entity/api/service.ts, packages/data-explorer-ui/src/hooks/useRequestFileLocation.ts
=> feat: send auth token for individual file download (#334)

packages/data-explorer-ui/src/components/Layout/components/BackPage/backPageView.styles.ts
=> feat: update BackPageView component style (#339)

packages/data-explorer-ui/src/apis/azul/common/entities.ts, packages/data-explorer-ui/src/hooks/useFetchEntity.tsx
=> feat: add response source field to fetch entity hook (#349)

packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/ExportToTerraReady/exportToTerraReady.tsx
=> feat: remove export to terra copy to clipboard response (#352)

packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/CreateTerraAccount/createTerraAccount.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/formStep.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.styles.ts, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.tsx, packages/data-explorer-ui/src/components/common/CustomIcon/components/FormStatusCompletedIcon/formStatusCompletedIcon.tsx, packages/data-explorer-ui/src/components/common/CustomIcon/components/FormStatusIncompleteIcon/formStatusIncompleteIcon.tsx, packages/data-explorer-ui/src/components/common/Section/section.styles.ts, packages/data-explorer-ui/src/styles/common/mixins/breakpoints.ts, packages/data-explorer-ui/src/styles/common/mixins/colors.ts, packages/data-explorer-ui/src/theme/common/components.ts
=> feat: create Terra set up component (#355)

packages/data-explorer-ui/src/components/ComponentCreator/ComponentCreator.tsx, packages/data-explorer-ui/src/components/ComponentCreator/components/RenderComponent/renderComponent.tsx
=> feat: update component creator component elements to use array index (#362)

packages/data-explorer-ui/src/components/ComponentCreator/ComponentCreator.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/ProfileComponent/components/AuthenticationMenu/authenticationMenu.stories.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/ProfileComponent/profileComponent.tsx, packages/data-explorer-ui/src/components/Login/login.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/providers/authentication.tsx
=> fix: fix unwanted render of terra set up form if user is verified (#360)

packages/data-explorer-ui/src/providers/exploreState.tsx
Closes https://github.com/altos-labs/data-browser/issues/268
Fix when creating explorer initial state.
=> fix: fixing entities default sorting #268

packages/data-explorer-ui/src/apis/azul/common/entities.ts, packages/data-explorer-ui/src/components/Export/components/ManifestDownload/components/ManifestDownloadEntity/components/FileManifestDownload/fileManifestDownload.tsx, packages/data-explorer-ui/src/components/Export/components/ManifestDownload/components/ManifestDownloadEntity/components/FileManifestSpreadsheet/fileManifestSpreadsheet.tsx, packages/data-explorer-ui/src/components/Export/components/ManifestDownload/components/ManifestDownloadEntity/manifestDownloadEntity.styles.ts, packages/data-explorer-ui/src/components/Export/components/ManifestDownload/components/ManifestDownloadEntity/manifestDownloadEntity.tsx, packages/data-explorer-ui/src/components/Export/export.styles.ts, packages/data-explorer-ui/src/hooks/useFileManifest/useFetchFilesFacets.ts, packages/data-explorer-ui/src/hooks/useFileManifest/useFetchSummary.ts, packages/data-explorer-ui/src/hooks/useFileManifest/useFileManifestDownload.ts, packages/data-explorer-ui/src/hooks/useFileManifest/useFileManifestSpreadsheet.ts, packages/data-explorer-ui/src/hooks/useFileManifest/useRequestFileManifest.ts, packages/data-explorer-ui/src/providers/fileManifestState.tsx
Closes #378.
Closes https://github.com/DataBiosphere/findable-ui/issues/16.
=> feat: create download entity manifest component (#378)

packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/ConnectTerraToNIHAccount/connectTerraToNIHAccount.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.tsx
=> feat: update terra onboarding form with nih account (#385)

packages/data-explorer-ui/src/components/Index/components/Hero/hero.styles.ts, packages/data-explorer-ui/src/components/Index/components/Hero/hero.tsx
=> feat: allow explore hero to optionally render title (#389)

packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/ConnectTerraToNIHAccount/connectTerraToNIHAccount.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/NIHAccountExpiryWarning/nihAccountExpiryWarning.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/providers/authentication.tsx
=> feat: add nih account linking check (#351)

packages/data-explorer-ui/src/components/Export/components/ExportMethod/exportMethod.styles.ts, packages/data-explorer-ui/src/components/Export/components/ExportMethod/exportMethod.tsx, packages/data-explorer-ui/src/hooks/useFileManifest/common/entities.ts, packages/data-explorer-ui/src/hooks/useFileManifest/useFetchFilesFacets.ts, packages/data-explorer-ui/src/providers/fileManifestState.tsx, packages/data-explorer-ui/src/theme/common/components.ts
Helpful for https://github.com/DataBiosphere/data-browser/issues/3625.
Closes #401.
=> feat: update usefetchfilefacets hook to return success state from fetch (#401)

packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/AcceptTerraTOS/acceptTerraTOS.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/ConnectTerraToNIHAccount/connectTerraToNIHAccount.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/CreateTerraAccount/createTerraAccount.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/formStep.styles.ts, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/formStep.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.styles.ts, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.tsx, packages/data-explorer-ui/src/components/common/CustomIcon/components/FormStatusCompletedIcon/formStatusCompletedIcon.tsx, packages/data-explorer-ui/src/providers/authentication.tsx, packages/data-explorer-ui/src/styles/common/mixins/colors.ts
=> feat: update terra onboarding widget to use numbered stepper (#397)

packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/NIHAccountExpiryWarning/nihAccountExpiryWarning.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.tsx
=> feat: notify user the era commons link has expired (#411)

packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Actions/components/Menu/components/Content/components/Slogan/slogan.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Actions/components/Menu/menu.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationDrawer/navigationDrawer.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Slogan/slogan.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Slogan/slogan.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/header.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Header/header.tsx, packages/data-explorer-ui/src/styles/common/mixins/breakpoints.ts
=> feat: update header menu style and slogan type (#414)

packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.styles.ts
=> feat: update terra set up form stepper styles (#415)

packages/data-explorer-ui/src/components/Layout/components/Footer/footer.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Footer/footer.tsx, packages/data-explorer-ui/src/components/Links/components/Link/link.tsx
=> feat: update footer ui (#421)

packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/AcceptTerraTOS/acceptTerraTOS.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/providers/authentication.tsx
=> feat: notify user tos has changed since they accepted and that they need to re-accept (#413)

packages/data-explorer-ui/src/common/entities.ts, packages/data-explorer-ui/src/components/Head/head.tsx, packages/data-explorer-ui/src/components/Layout/components/Footer/footer.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/common/utils.ts, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Actions/actions.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Actions/components/Menu/components/Toolbar/toolbar.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Actions/components/Menu/menu.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Logo/logo.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenu/navigationMenu.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenuItems/navigationMenuItems.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Navigation/navigation.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Navigation/navigation.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/header.stories.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/header.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Header/header.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/config/utils.ts
=> feat: update header to optionally right align navigation links (#429)

packages/data-explorer-ui/src/components/Filter/components/Filter/filter.styles.ts, packages/data-explorer-ui/src/components/Filter/components/FilterLabel/filterLabel.styles.ts, packages/data-explorer-ui/src/components/Filter/components/FilterList/filterList.styles.ts, packages/data-explorer-ui/src/components/Filter/components/SearchAllFilters/common/constants.ts, packages/data-explorer-ui/src/components/Filter/components/SearchAllFilters/components/AutocompletePopper/autocompletePopper.styles.ts, packages/data-explorer-ui/src/components/Filter/components/SearchAllFilters/components/AutocompletePopper/autocompletePopper.tsx, packages/data-explorer-ui/src/components/Filter/components/SearchAllFilters/components/VariableSizeList/VariableSizeList.tsx, packages/data-explorer-ui/src/components/Filter/components/SearchAllFilters/searchAllFilters.tsx, packages/data-explorer-ui/src/components/Filter/components/SearchAllFiltersSearch/components/SearchCloseButton/searchCloseButton.styles.ts, packages/data-explorer-ui/src/components/Filter/components/SearchAllFiltersSearch/components/SearchCloseButton/searchCloseButton.tsx, packages/data-explorer-ui/src/components/Filter/components/SearchAllFiltersSearch/searchAllFiltersSearch.styles.ts, packages/data-explorer-ui/src/components/Filter/components/SearchAllFiltersSearch/searchAllFiltersSearch.tsx, packages/data-explorer-ui/src/components/Layout/components/Sidebar/components/SidebarDrawer/sidebarDrawer.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Sidebar/components/SidebarDrawer/sidebarDrawer.tsx, packages/data-explorer-ui/src/components/Layout/components/Sidebar/sidebar.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Sidebar/sidebar.tsx, packages/data-explorer-ui/src/theme/common/components.ts
=> feat: update find all filters ui (#445)

packages/data-explorer-ui/src/components/Layout/components/Footer/footer.tsx
=> feat: update footer links (#452)

packages/data-explorer-ui/src/components/Layout/components/Footer/footer.stories.tsx, packages/data-explorer-ui/src/components/Layout/components/Footer/footer.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Footer/footer.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Logo/logo.tsx, packages/data-explorer-ui/src/config/utils.ts
=> feat: update footer logo type to a react node (#454)

packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/entity/api/service.ts, packages/data-explorer-ui/src/hooks/useCatalog.ts, packages/data-explorer-ui/src/hooks/useFileManifest/useFileManifestDownload.ts, packages/data-explorer-ui/src/hooks/useFileManifest/useFileManifestSpreadsheet.ts, packages/data-explorer-ui/src/providers/fileManifestState.tsx, packages/data-explorer-ui/src/shared/utils.ts
=> feat: only specify catalog # once (not twice) (#290)

packages/data-explorer-ui/src/components/common/Tabs/tabs.styles.ts, packages/data-explorer-ui/src/components/common/Tabs/tabs.tsx, packages/data-explorer-ui/src/theme/common/components.ts
=> fix: fix tab ui (#436)

packages/data-explorer-ui/src/components/Project/components/Citation/citation.styles.ts, packages/data-explorer-ui/src/components/Project/components/Citation/citation.tsx, packages/data-explorer-ui/src/components/common/Section/components/CollapsableSection/collapsableSection.styles.ts
=> fix: fix citation on mobile (#464)

packages/data-explorer-ui/src/components/Layout/components/Footer/footer.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Footer/footer.tsx
=> feat: make footer links optionally render (#463)

packages/data-explorer-ui/src/config/entities.ts
=> feat: add overrides to site config entity (#467)

packages/data-explorer-ui/src/hooks/useEntityService.ts, packages/data-explorer-ui/src/hooks/useFetchEntity.tsx
=> fix: update entity detail view to only fetch entity when required (#469)

packages/data-explorer-ui/src/apis/azul/common/entities.ts, packages/data-explorer-ui/src/entity/api/service.ts, packages/data-explorer-ui/src/hooks/useEntityList.ts
=> fix: fix error generated when switching between index tabs (#471)

packages/data-explorer-ui/src/entity/api/service.ts, packages/data-explorer-ui/src/entity/service/model.ts, packages/data-explorer-ui/src/hooks/useCatalog.ts, packages/data-explorer-ui/src/hooks/useEntityList.ts, packages/data-explorer-ui/src/hooks/useEntityService.ts, packages/data-explorer-ui/src/hooks/useFetchEntity.tsx, packages/data-explorer-ui/src/hooks/useSummary.ts, packages/data-explorer-ui/src/hooks/useURLFilterParams.ts, packages/data-explorer-ui/src/hooks/useUpdateURLSearchParams.ts, packages/data-explorer-ui/src/providers/exploreState.tsx
=> feat: set catalog from url (#474)

packages/data-explorer-ui/src/config/entities.ts
=> feat: update EntityConfig interface with overrides (#483)

packages/data-explorer-ui/src/components/common/EllipsisContent/ellipsisContent.styles.ts, packages/data-explorer-ui/src/components/common/EllipsisContent/ellipsisContent.tsx, packages/data-explorer-ui/src/hooks/useResizeObserver.ts
=> feat: add ellipsis content component (#485)

packages/data-explorer-ui/src/components/common/EllipsisContent/ellipsisContent.styles.ts
=> fix: fix ellipsis content component styles (#489)

packages/data-explorer-ui/src/entity/apicf/service.ts, packages/data-explorer-ui/src/entity/service/model.ts, packages/data-explorer-ui/src/hooks/useEntityService.ts
=> feat: update server-side fetch, client-side filtering service (#501)

packages/data-explorer-ui/src/components/Layout/components/BackPage/backPageView.styles.ts
=> fix: fix visible css on new page load bug (#506)

packages/data-explorer-ui/src/components/Export/components/ManifestDownload/components/ManifestDownloadEntity/components/FileManifestDownload/fileManifestDownload.tsx, packages/data-explorer-ui/src/components/Export/components/ManifestDownload/components/ManifestDownloadEntity/components/FileManifestSpreadsheet/fileManifestSpreadsheet.tsx, packages/data-explorer-ui/src/components/common/ButtonGroup/buttonGroup.tsx
=> fix: revert button group component (#511)

packages/data-explorer-ui/src/components/Layout/components/AppLayout/appLayout.styles.ts
=> fix: fix app layout (#515)

packages/data-explorer-ui/src/hooks/useFeatureFlag/common/entities.ts, packages/data-explorer-ui/src/hooks/useFeatureFlag/common/utils.ts, packages/data-explorer-ui/src/hooks/useFeatureFlag/useFeatureFlag.ts
=> feat: add hook to handle local storage (#508)

packages/data-explorer-ui/src/components/Layout/components/Sidebar/components/SidebarButton/sidebarButton.styles.ts, packages/data-explorer-ui/src/components/Layout/components/Sidebar/components/SidebarButton/sidebarButton.tsx, packages/data-explorer-ui/src/providers/exploreState.tsx, packages/data-explorer-ui/src/providers/exploreState/constants.ts, packages/data-explorer-ui/src/providers/exploreState/utils.ts, packages/data-explorer-ui/src/views/ExploreView/exploreView.tsx
=> feat: add count to mobile filter button (#522)

packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/providers/authentication.tsx
=> feat: update authentication to optionally configure nih endpoint (#526)

packages/data-explorer-ui/src/components/Error/error.styles.ts, packages/data-explorer-ui/src/components/Error/error.tsx
=> fix: fix error boundary layout (#523)

packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/NIHAccountExpiryWarning/nihAccountExpiryWarning.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.tsx
=> fix: fix flash of terra set up form (#539)

packages/data-explorer-ui/src/components/common/Banner/components/SessionTimeout/sessionTimeout.styles.ts, packages/data-explorer-ui/src/components/common/Banner/components/SessionTimeout/sessionTimeout.tsx, packages/data-explorer-ui/src/hooks/useSessionTimeout.ts, packages/data-explorer-ui/src/providers/authentication.tsx, packages/data-explorer-ui/src/styles/common/mixins/breakpoints.ts
=> feat: add session timeout banner (#534)

packages/data-explorer-ui/src/apis/azul/common/entities.ts, packages/data-explorer-ui/src/hooks/useFetchEntity.tsx, packages/data-explorer-ui/src/views/EntityDetailView/entityDetailView.tsx
=> fix: fix fetch of entity (#476)

packages/data-explorer-ui/src/providers/exploreState.tsx, packages/data-explorer-ui/src/providers/exploreState/payloads/entities.ts
=> fix: fix explore state when authentication state is updated (#536)

packages/data-explorer-ui/src/components/Detail/components/AccessibilityBadge/accessibilityBadge.tsx, packages/data-explorer-ui/src/components/common/StatusBadge/statusBadge.tsx
=> feat: create new accessibility status for entity detail (#541)

packages/data-explorer-ui/src/components/ComponentCreator/ComponentCreator.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/AcceptTerraTOS/acceptTerraTOS.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/NIHAccountExpiryWarning/nihAccountExpiryWarning.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Actions/components/Authentication/authentication.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Actions/components/Authentication/components/AuthenticationMenu/authenticationMenu.stories.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Actions/components/Authentication/components/AuthenticationMenu/authenticationMenu.tsx, packages/data-explorer-ui/src/components/Login/login.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/hooks/useAuthentication/common/constants.ts, packages/data-explorer-ui/src/hooks/useAuthentication/common/entities.ts, packages/data-explorer-ui/src/hooks/useAuthentication/common/utils.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useAuthentication.tsx, packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationComplete.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationForm.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationNIHExpiry.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useFetchGoogleProfile.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useFetchTerraNIHProfile.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useFetchTerraProfile.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useFetchTerraTermsOfService.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useTokenClient.ts, packages/data-explorer-ui/src/hooks/useEntityList.ts, packages/data-explorer-ui/src/hooks/useFetchEntity.tsx, packages/data-explorer-ui/src/hooks/useFileManifest/useFetchFilesFacets.ts, packages/data-explorer-ui/src/hooks/useFileManifest/useFetchSummary.ts, packages/data-explorer-ui/src/hooks/useRequestFileLocation.ts, packages/data-explorer-ui/src/hooks/useSummary.ts, packages/data-explorer-ui/src/providers/authentication.tsx, packages/data-explorer-ui/src/providers/exploreState.tsx
=> fix: fix flash of terra set up form (#552)

packages/data-explorer-ui/src/providers/authentication.tsx, packages/data-explorer-ui/src/providers/exploreState.tsx
=> fix: query links and entity links hang (#563)

packages/data-explorer-ui/src/components/Head/head.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/hooks/useEntityHeadTitle.ts, packages/data-explorer-ui/src/views/EntityDetailView/entityDetailView.tsx
=> feat: app title (#565)

packages/data-explorer-ui/src/theme/common/components.ts
=> fix: update tooltip touch interaction for hand held devices (#575)

packages/data-explorer-ui/src/components/common/Title/title.styles.ts
=> fix: update entity detail page title style (#574)

packages/data-explorer-ui/src/components/ComponentCreator/ComponentCreator.tsx, packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/AcceptTerraTOS/acceptTerraTOS.tsx, packages/data-explorer-ui/src/config/entities.ts, packages/data-explorer-ui/src/entity/apicf/service.ts, packages/data-explorer-ui/src/entity/service/model.ts, packages/data-explorer-ui/src/hooks/useAuthentication/common/constants.ts, packages/data-explorer-ui/src/hooks/useAuthentication/common/entities.ts, packages/data-explorer-ui/src/hooks/useAuthentication/common/utils.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationComplete.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationForm.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationNIHExpiry.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationStatus.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useFetchGoogleProfile.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useFetchTerraNIHProfile.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useFetchTerraProfile.ts, packages/data-explorer-ui/src/hooks/useAuthentication/useFetchTerraTermsOfService.ts, packages/data-explorer-ui/src/hooks/useEntityList.ts, packages/data-explorer-ui/src/providers/authentication.tsx, packages/data-explorer-ui/tests/authentication.test.ts, packages/data-explorer-ui/tests/useAuthenticationStatus.test.ts
=> feat: update authentication hook to handle google login in isolation (#576)

packages/data-explorer-ui/src/components/common/Typography/TypographyWordBreak/TypographyWordBreak.tsx
=> feat: add typography component with word breaking (#584)

packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Logo/logo.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenuItems/navigationMenuItems.tsx, packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Navigation/navigation.tsx, packages/data-explorer-ui/src/components/Links/components/Link/link.tsx, packages/data-explorer-ui/src/components/common/Button/components/CallToActionButton/callToActionButton.tsx, packages/data-explorer-ui/src/components/common/Button/components/HelpIconButton/helpIconButton.tsx, packages/data-explorer-ui/src/components/common/Card/components/CardActionArea/cardActionArea.tsx, packages/data-explorer-ui/src/components/common/Socials/socials.tsx
=> fix: implement noopener noreferrer on external links (#588)

packages/data-explorer-ui/src/apis/azul/common/entities.ts, packages/data-explorer-ui/src/entity/api/service.ts, packages/data-explorer-ui/src/entity/common/client.ts, packages/data-explorer-ui/src/entity/service/model.ts, packages/data-explorer-ui/src/hooks/useFetchEntity.tsx, packages/data-explorer-ui/src/hooks/useUpdateURLCatalogParam.ts, packages/data-explorer-ui/src/views/EntityDetailView/entityDetailView.tsx
=> feat: update entity detail page to view entities from other catalogs (#573)
