clevercanary/data-explorer

- packages/data-explorer-ui/package-lock.json
Closes clevercanary/data-browser#839.
> fix: corrected package lock version #839

- packages/data-explorer-ui/package-lock.json
- packages/data-explorer-ui/package.json
Closes clevercanary/data-browser#839.
> fix: updated patch version #839

- packages/data-explorer-ui/.storybook/main.ts
PR might affect a lot of stories, basically when any inherit is used. From my point of view it is totally correct way: if we extend props, allowing them in components, than we should display them in storybook. But sometimes we want to limit the number of them.
Any hints which stories might be affected at welcome
> feat: show mui props in stories if component props extend them

- packages/data-explorer-ui/src/entity/api/service.ts
Closes #107 
Replacing the use of fetch to axios.
OBS: It seems that API's catalogs have changed. **I was only able to test this with dev:hca-dpc** and had to change the catalog to dcp3. I have tried to use the `data-explore`s current version to check if the error was related to something that I did on this PR, but error happens on that version as well.
> feat: using axios to handle api calls #107

- packages/data-explorer-ui/src/hooks/useEntityListRelatedView.ts
The ProcessRelatedResponse action was firing on every tab change even if no relatedSearchFn was configured. 
I updated the related results useEffect to test if the relatedSearchFn exists before sending a ProcessRelatedResponse action.
> fix: only update related view if configured (#200)

- packages/data-explorer-ui/src/components/Layout/components/ContentLayout/contentLayout.styles.ts
- packages/data-explorer-ui/src/components/Layout/components/ContentLayout/contentLayout.tsx
- packages/data-explorer-ui/src/views/ContentView/contentView.tsx
Closes Databiosphere/findable-ui#7
New layout with centre channel, and left nav created. Scaffolding in place for right nav (even though it was out of scope).
> feat: create layout component (#7)

- packages/data-explorer-ui/src/hooks/useEntityService.ts
Closes #81 
Changes: Always use the entity config from the state (and not from the incoming AzulStaticResponse) to keep the state in sync and the entity list type always matching the entity type.
Tests: I tried this on AnIVL Catalog,  HCA DCP, AnVIL CMG. This removes the double hit of the BE on changing tabs in Azul mode and seems to have no change in catalog mode.
Can you try testing it out locally as well please? @frano-m 
Thanks,
D
> fix: use current tab value always (#81)

- packages/data-explorer-ui/package-lock.json
- packages/data-explorer-ui/package.json
- packages/data-explorer-ui/src/providers/authentication.tsx
Closes https://github.com/clevercanary/data-explorer/issues/210
- Adding `react-idle-timer` as peerDependency
- Adding `sessionTimeout` prop to `AuthProvider`.
> feat: adding session timeout #210

- packages/data-explorer-ui/src/apis/azul/common/entities.ts
- packages/data-explorer-ui/src/components/Export/common/entities.ts
- packages/data-explorer-ui/src/components/Export/common/utils.ts
- packages/data-explorer-ui/src/components/Export/components/DownloadCurlCommand/components/DownloadCurlCommandNotStarted/downloadCurlCommandNotStarted.styles.ts
- packages/data-explorer-ui/src/components/Export/components/DownloadCurlCommand/components/DownloadCurlCommandNotStarted/downloadCurlCommandNotStarted.tsx
- packages/data-explorer-ui/src/components/Export/components/DownloadCurlCommand/components/DownloadCurlCommandReady/downloadCurlCommandReady.tsx
- packages/data-explorer-ui/src/components/Export/components/DownloadCurlCommand/components/DownloadEntityCurlCommand/downloadEntityCurlCommand.tsx
- packages/data-explorer-ui/src/components/Export/components/ExportEntityToTerra/exportEntityToTerra.tsx
- packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/ExportToTerraNotStarted/exportToTerraNotStarted.tsx
- packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/ExportToTerraReady/exportToTerraReady.tsx
- packages/data-explorer-ui/src/components/Export/export.styles.ts
- packages/data-explorer-ui/src/hooks/useRequestFileLocation.ts
- packages/data-explorer-ui/src/providers/detailState.tsx
- packages/data-explorer-ui/src/views/ExportToTerraView/mainColumn.tsx
Closes #242.
Closes https://github.com/DataBiosphere/findable-ui/issues/12.
- Breaking change for use of `ExportEntityToTerra`.
> feat: create download entity curl component (#242)

- packages/data-explorer-ui/src/components/common/Card/card.tsx
> feat: update card component with paper prop (#254)

- packages/data-explorer-ui/src/components/Layout/components/BackPage/components/BackPageHero/backPageHero.tsx
- packages/data-explorer-ui/src/components/Layout/components/BackPage/components/BackPageHero/components/SubTitle/subTitle.tsx
- packages/data-explorer-ui/src/components/common/Title/title.tsx
Closes #254.
Closes https://github.com/clevercanary/data-explorer/issues/199.
> feat: update backpagehero component to optionally render icon and by line (#258)

- packages/data-explorer-ui/src/components/Table/table.tsx
- packages/data-explorer-ui/src/hooks/useEntityList.ts
- packages/data-explorer-ui/src/hooks/useLocation.ts
- packages/data-explorer-ui/src/hooks/useURLFilterParams.ts
- packages/data-explorer-ui/src/providers/exploreState.tsx
- packages/data-explorer-ui/src/views/ExploreView/exploreView.tsx
I have tested this, but please test thoroughly on both client and server-side filtering.
How this works basically is:
1. The user selects a filter
2. The onFilterChange is fired, dispatching the UpdateFilter action
3. The table filters
4. Independtly a new hook updates the queryString from the filterState using [shallow](https://nextjs.org/docs/pages/building-your-application/routing/linking-and-navigating#shallow-routing)=true on push to prevent reloading the page.
When a new page is hit:
1. useURLFilterParams is called in exploreState.tsx to set the initial state of the filter from the URL params
> feat: add query params to url (#223)

- packages/data-explorer-ui/src/components/Filter/components/SearchAllFilters/searchAllFilters.styles.ts
- packages/data-explorer-ui/src/components/Filter/components/SearchAllFilters/searchAllFilters.tsx
In addition to resolving the issues with wrapping and spaces, I've also made it so that the highlight only has horizontal padding when the edge is next to whitespace or the edge of the text, in order to better match the mock (where e.g. the highlighted "liver" in "Celliver Biotechnology Inc" appears to have right padding but not left padding)
> fix: use inline element for highlight and adjust horizontal padding (#296)

- packages/data-explorer-ui/src/entity/api/service.ts
- packages/data-explorer-ui/src/entity/service/model.ts
- packages/data-explorer-ui/src/hooks/useFetchEntity.tsx
> feat: optional pre-render of entity detail tabs (#259)

- packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/ExportToTerraReady/exportToTerraReady.tsx
> fix: add rel=noopener noreferrer to the "export to terra" link (#345)

- packages/data-explorer-ui/package-lock.json
- packages/data-explorer-ui/package.json
- packages/data-explorer-ui/src/components/Table/table.tsx
~~One note -- I wasn't sure how best to insert the padding for the virtualization, since it's the whole page's scroll height that needs to be padded, and so in theory the padding could be put anywhere above and below the table contents. Initially I didn't use the window virtualizer and was just virtualizing the table itself, and had to insert extra rows to act as padding, but after switching to the window virtualizer, I ended up putting the padding on the table element, because that allows it to be just CSS padding while otherwise being as close as possible to the table contents.~~
I've realized that when the virtualization can't keep up with the scroll speed, using rows as padding behaves better than putting CSS padding on the table. (When the padding is outside the table contents, the …
> feat: virtualize entity lists

- packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/AcceptTerraTOS/acceptTerraTOS.tsx
- packages/data-explorer-ui/src/components/Export/components/ExportToTerra/components/TerraSetUpForm/terraSetUpForm.tsx
- packages/data-explorer-ui/src/providers/authentication.tsx
Closes #395.
Addresses https://github.com/DataBiosphere/data-browser/issues/3593.
> fix: prevent sending auth token to azul when terra tos not accepted (#395)

- packages/data-explorer-ui/src/config/entities.ts
> feat: update site config to allow project specific markdown pages (#407)

- packages/data-explorer-ui/src/components/Index/components/Hero/components/Summaries/summaries.styles.ts
- packages/data-explorer-ui/src/components/Index/components/Hero/components/Summaries/summaries.tsx
- packages/data-explorer-ui/src/components/Index/components/Hero/hero.styles.ts
- packages/data-explorer-ui/src/components/Index/index.styles.ts
- packages/data-explorer-ui/src/components/Table/table.tsx
- packages/data-explorer-ui/src/components/common/Dot/dot.tsx
> feat: update summary and export ui (#428)

- packages/data-explorer-ui/package-lock.json
Closes #444
This PR reduces the vulnerabilities from `6 moderate and 9 critical` to `2 moderate`. For the last 2 to be resolved we would need to upgrade `next.js`
> chore: resolving vulnerabilities #444

- packages/data-explorer-ui/src/components/Filter/components/FilterTag/filterTag.tsx
~~Currently a draft because @NoopDog mentioned that we might need to determine how big the gap between the tooltip and the tag should be~~
~~Additionally: Is `useWindowResize` a good way of determining when to re-check whether the tag label is overflowing? Are there other situations in which that might change? Or, conversely, is there a simpler set of circumstances in which it can?~~
> feat: add tooltip when filter tag label is truncated (#438)

- packages/data-explorer-ui/src/components/Error/error.tsx
- packages/data-explorer-ui/src/components/ErrorBoundary/errorBoundary.tsx
- packages/data-explorer-ui/src/providers/exploreState.tsx
- packages/data-explorer-ui/src/providers/initial.ts
> fix: reseting explore state on error component #433

- packages/data-explorer-ui/src/components/Export/components/DownloadCurlCommand/downloadCurlCommand.tsx
- packages/data-explorer-ui/src/components/Export/components/ExportToTerra/exportToTerra.tsx
- packages/data-explorer-ui/src/components/Export/components/ManifestDownload/manifestDownload.tsx
- packages/data-explorer-ui/src/entity/api/service.ts
- packages/data-explorer-ui/src/hooks/useFileManifest/useFileManifest.ts
- packages/data-explorer-ui/src/hooks/useFileManifest/useFileManifestDownload.ts
- packages/data-explorer-ui/src/hooks/useRequestFileLocation.ts
Closes https://github.com/DataBiosphere/data-browser/issues/3694
> feat: using put method for files manifest requests #3694

- packages/data-explorer-ui/src/components/Table/common/utils.ts
- packages/data-explorer-ui/src/components/Table/components/EntityViewToggle/entityViewToggle.tsx
- packages/data-explorer-ui/src/components/Table/table.tsx
- packages/data-explorer-ui/src/components/TableCreator/tableCreator.tsx
- packages/data-explorer-ui/src/config/entities.ts
- packages/data-explorer-ui/src/config/utils.ts
- packages/data-explorer-ui/src/entity/api/service.ts
- packages/data-explorer-ui/src/entity/apicf/client.ts
- packages/data-explorer-ui/src/entity/apicf/service.ts
- packages/data-explorer-ui/src/entity/service/factory.ts
- packages/data-explorer-ui/src/entity/service/model.ts
- packages/data-explorer-ui/src/hooks/useEntityList.ts
- packages/data-explorer-ui/src/hooks/useEntityService.ts
- packages/data-explorer-ui/src/hooks/useExploreMode.ts
- packages/data-explorer-ui/src/hooks/useFetchEntity.tsx
- packages/data-explorer-ui/src/providers/exploreState.tsx
- packages/data-explorer-ui/src/providers/exploreState/constants.ts
- packages/data-explorer-ui/src/providers/exploreState/payloads/entities.ts
- packages/data-explorer-ui/src/providers/exploreState/utils.ts
- packages/data-explorer-ui/src/views/ExploreView/exploreView.tsx
> feat: create explorer mode to handle server-side fetches with client-side filtering (#495)

- packages/data-explorer-ui/src/components/common/Banner/banner.tsx
- packages/data-explorer-ui/src/components/common/Banner/components/CookieBanner/cookieBanner.styles.ts
- packages/data-explorer-ui/src/components/common/Banner/components/CookieBanner/cookieBanner.tsx
- packages/data-explorer-ui/src/components/common/Banner/components/DismissibleBanner/dismissibleBanner.tsx
- packages/data-explorer-ui/src/components/common/Button/components/ButtonOutline/buttonOutline.styles.ts
- packages/data-explorer-ui/src/components/common/Button/components/ButtonOutline/buttonOutline.tsx
- packages/data-explorer-ui/types/data-explorer-ui.d.ts
> feat: create dismissible cookie banner (#543)

- packages/data-explorer-ui/src/components/common/Banner/components/CookieBanner/cookieBanner.tsx
- packages/data-explorer-ui/src/components/common/Banner/components/DismissibleBanner/dismissibleBanner.tsx
- packages/data-explorer-ui/src/hooks/useFeatureFlag/common/utils.ts
- packages/data-explorer-ui/src/hooks/useFeatureFlag/useFeatureFlag.ts
- packages/data-explorer-ui/src/hooks/useLocalStorage/common/utils.ts
- packages/data-explorer-ui/src/hooks/useLocalStorage/useLocalStorage.ts
> fix: fix dismissible banner ssr bug (#547)

- packages/data-explorer-ui/src/components/Layout/components/Header/common/utils.ts
- packages/data-explorer-ui/src/components/Layout/components/Header/components/Content/components/Actions/components/Menu/components/Toolbar/toolbar.tsx
- packages/data-explorer-ui/src/components/Layout/components/Header/header.tsx
> feat: update header component to take additional actions (#560)
